game_info:
  game_title: "Tower Defense Game"
  game_version: 0.1
  game_dev_date: Nov 24, 2024
  screen_width: 800
  screen_height: 600
  fps: 60

keys:
  key_play: 'p'
  key_pause: 'space'
  key_exit: 'x'
  key_quit: 'q'
  key_escape: 'escape'

regions:
  play: [350, 150, 450, 200]       # Horizontally centered, top margin
  setup: [350, 210, 450, 260]      # 10px margin between play and setup
  restore: [350, 270, 450, 320]    # 10px margin between setup and restore
  exit: [350, 330, 450, 380]       # 10px margin between restore and exit    
  main_menu: [0, 100, 0, 50] 
  pause: [0, 100, 0, 50] 
  quit: [0, 100, 0, 50]   

state_transitions:
  - [initial, main_menu, "auto"]
  - [main_menu, play, "key_play | region play"]
  - [main_menu, setup, "region setup"]
  - [main_menu, restore, "region restore"]
  - [main_menu, exit_game, "key_exit | region exit"]
  - [setup, main_menu, "key_escape"]
  - [restore, main_menu, "key_escape"]  
  - [play, pause, "key_pause"]
  - [pause, play, "key_play"]
  - [play, win_game, "cond win_game"]
  - [play, win_level, "cond win_level"]
  - [play, lose_level, "cond lose_level"]
  - [play, power_up, "cond power_up"]
  - [play, quit, "key_quit"]
  - [quit, main_menu, "auto"]


  